### PR TITLE
README.md pages redirect to workshop view URL

### PR DESCRIPTION
**Pull request by maxwofford**
/personal_website/README.md redirects to /personal_website/

### CODE REVIEW

**Comment by maxwofford** [comment]
_**This should not be merged yet.**_

**Comment by zachlatta** [comment]
Any updates on this?

**Comment by zachlatta** [comment]
Assigning back to you while I can't merge.

**Comment by maxwofford** [comment]
We shouldn't need this feature after https://github.com/hackclub/hackclub/pull/911

**Pull request closed without merging**
